### PR TITLE
fix: handle LEFTHOOK_QUIET when there is no skip_output in config

### LINKED ISSUE #623: `LEFTHOOK_QUIET` enviroment variable doesn't work
### :wrench: Summary

Lefthook doesn't skip any output else if [set the values to the `LEFTHOOK_QUIET` environment variable](https://github.com/evilmartians/lefthook/blob/v1.6.1/docs/usage.md#lefthook_quiet).

### Lefthook version

`1.5.6 dce1a0b6e0e8e9dc38d5376dad15ce29a7f137a8` - `1.6.1 e69adc10c99fd8887673a8b18894082453c6ceaf`

Lefthook v1.5.5 doesn't have the problem.

### Steps to reproduce

Run the following bash script.

`reproduce.sh`

``` bash
#!/usr/bin/env bash

mkdir not_work_LEFTHOOK_QUIET
cd not_work_LEFTHOOK_QUIET

git init --quiet

cat<<'HERE'>lefthook.toml
[foo]
[foo.commands]
[foo.commands.bar]
run = 'echo Hello World'
HERE

run_lefthook() {
  filename="lefthook_$1"

  wget \
    --quiet \
    --output-document="$filename" \
    https://github.com/evilmartians/lefthook/releases/download/v"$1"/lefthook_"$1"_Linux_x86_64

  chmod +x "$filename"

  export LEFTHOOK_QUIET=meta,summary,empty_summary,execution

  echo "========================================="
  printf 'version: %s\n' "$(./"$filename" version -f)"
  echo "========================================="
  set -x
  ./"$filename" install
  ./"$filename" run foo
  set +x
}

for patch_version in 5 6; do
  run_lefthook "1.5.$patch_version"
done
```

- OS: Ubuntu 20.04 (WSL2)

### Expected results

``` console
$ LEFTHOOK_QUIET=meta,summary,empty_summary,execution lefthook run foo
$
```

### Actual results

``` console
$ LEFTHOOK_QUIET=meta,summary,empty_summary,execution lefthook run foo
╭───────────────────────────────╮
│ 🥊 lefthook v1.5.6  hook: foo │
╰───────────────────────────────╯
┃  bar ❯

Hello World


  ────────────────────────────────────
summary: (done in 0.00 seconds)
✔️  bar
$
```

### Possible Solution

Lefthook have had the problem since the f32e497a9813b5495ba33f7bf6d9c6acc259d79a commit.

If `LEFTHOOK_QUITE=''` disable all output like a [`skip_output: false` of Lefthook configuration](https://github.com/evilmartians/lefthook/blob/v1.6.1/docs/configuration.md#skip_output), I would be happy.

### Logs / Screenshots

``` console
$ LEFTHOOK_VERBOSE=1 bash reproduce.sh
=========================================
version: 1.5.5 9b072e6622857ceb8d40a173ba39ae97afb35957
=========================================
+ ./lefthook_1.5.5 install
│ [lefthook] cmd: [git rev-parse --show-toplevel]
│ [lefthook] dir:
│ [lefthook] err: <nil>
│ [lefthook] out: /home/hituzi_no_sippo/workspace/my_projects/hooks_for_lefthook/reproduce/not_work_LEFTHOOK_QUIET

│ [lefthook] cmd: [git rev-parse --git-path hooks]
│ [lefthook] dir:
│ [lefthook] err: <nil>
│ [lefthook] out: .git/hooks

│ [lefthook] cmd: [git rev-parse --git-path info]
│ [lefthook] dir:
│ [lefthook] err: <nil>
│ [lefthook] out: .git/info

│ [lefthook] cmd: [git rev-parse --git-dir]
│ [lefthook] dir:
│ [lefthook] err: <nil>
│ [lefthook] out: .git

│ Searching config in:/home/hituzi_no_sippo/workspace/my_projects/hooks_for_lefthook/reproduce/not_work_LEFTHOOK_QUIET
sync hooks: ✔️ (foo)
+ ./lefthook_1.5.5 run foo
│ [lefthook] cmd: [git rev-parse --show-toplevel]
│ [lefthook] dir:
│ [lefthook] err: <nil>
│ [lefthook] out: /home/hituzi_no_sippo/workspace/my_projects/hooks_for_lefthook/reproduce/not_work_LEFTHOOK_QUIET

│ [lefthook] cmd: [git rev-parse --git-path hooks]
│ [lefthook] dir:
│ [lefthook] err: <nil>
│ [lefthook] out: .git/hooks

│ [lefthook] cmd: [git rev-parse --git-path info]
│ [lefthook] dir:
│ [lefthook] err: <nil>
│ [lefthook] out: .git/info

│ [lefthook] cmd: [git rev-parse --git-dir]
│ [lefthook] dir:
│ [lefthook] err: <nil>
│ [lefthook] out: .git

+ set +x
=========================================
version: 1.5.6 dce1a0b6e0e8e9dc38d5376dad15ce29a7f137a8
=========================================
+ ./lefthook_1.5.6 install
│ [lefthook] cmd: [git rev-parse --show-toplevel]
│ [lefthook] dir:
│ [lefthook] err: <nil>
│ [lefthook] out: /home/hituzi_no_sippo/workspace/my_projects/hooks_for_lefthook/reproduce/not_work_LEFTHOOK_QUIET

│ [lefthook] cmd: [git rev-parse --git-path hooks]
│ [lefthook] dir:
│ [lefthook] err: <nil>
│ [lefthook] out: .git/hooks

│ [lefthook] cmd: [git rev-parse --git-path info]
│ [lefthook] dir:
│ [lefthook] err: <nil>
│ [lefthook] out: .git/info

│ [lefthook] cmd: [git rev-parse --git-dir]
│ [lefthook] dir:
│ [lefthook] err: <nil>
│ [lefthook] out: .git

│ Searching config in:/home/hituzi_no_sippo/workspace/my_projects/hooks_for_lefthook/reproduce/not_work_LEFTHOOK_QUIET
sync hooks: ✔️ (foo)
+ ./lefthook_1.5.6 run foo
│ [lefthook] cmd: [git rev-parse --show-toplevel]
│ [lefthook] dir:
│ [lefthook] err: <nil>
│ [lefthook] out: /home/hituzi_no_sippo/workspace/my_projects/hooks_for_lefthook/reproduce/not_work_LEFTHOOK_QUIET

│ [lefthook] cmd: [git rev-parse --git-path hooks]
│ [lefthook] dir:
│ [lefthook] err: <nil>
│ [lefthook] out: .git/hooks

│ [lefthook] cmd: [git rev-parse --git-path info]
│ [lefthook] dir:
│ [lefthook] err: <nil>
│ [lefthook] out: .git/info

│ [lefthook] cmd: [git rev-parse --git-dir]
│ [lefthook] dir:
│ [lefthook] err: <nil>
│ [lefthook] out: .git

╭───────────────────────────────╮
│ 🥊 lefthook v1.5.6  hook: foo │
╰───────────────────────────────╯
┃  bar ❯

Hello World


  ────────────────────────────────────
summary: (done in 0.00 seconds)
✔️  bar
+ set +x
$
```

### PR DESCRIPTION
**Pull request by prog-supdex**
Closes #623 

#### :zap: Summary

Handles situations when only `LEFTHOOK_QUIET` exists, without `skip_output` in the `lefthook.yml` file

#### :ballot_box_with_check: Checklist

- [x] Check locally
- [x] Add tests
- [ ] Add documentation

### CODE REVIEW

File: internal/log/skip_settings_test.go [hunk 1]
```diff
@@ -106,4 +106,21 @@ func TestSkipSetting(t *testing.T) {
...
+		}
+
+		if !settings.SkipSuccess() {
+			t.Errorf("expected SkipSuccess to be true")
+		}
+
+		if settings.SkipFailure() {
+			t.Errorf("expected SkipFailure to be false")
+		}
+	})
```
Comment (mrexox) [inline internal/log/skip_settings_test.go:125]: What if we extend the previous test to include `tags` variable? I think we can add a testcase with `tags: "meta,success"` and `settings: nil`

**Review by mrexox — APPROVED** [review]
This fix solves the issue! Thank you! I only have a nitpick about the tests

File: internal/log/skip_settings_test.go (hunk 1 above)
Comment (prog-supdex) [reply internal/log/skip_settings_test.go]: done!
